# my global config
global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s 


rule_files:
   - "rules.yml"

alerting:
   alertmanagers:
   - static_configs:
     - targets: 
        - localhost:9093
       
  

  
scrape_configs:
  
  - job_name: 'prometheus'

   

    static_configs:
    #- targets: ['localhost:9090']
    - targets:
        - localhost:9090
   
  - job_name: 'node_exporter'

   

    static_configs:
    - targets: 
        - localhost:9182
    
    
  - job_name: 'flask_app'

   

    static_configs:
    - targets: 
        - localhost:8010


